"""
Tính Arena Size và xuất ai_config.h đồng bộ Laptop ↔ ESP32
Chuẩn: README.md:133 (768KB+350KB+32KB), mo_ta_project.md:50, CAC_FILE_CHINH_NHIEU.md:2.2
"""
import os

# [4.1 REALTIME] Tối ưu bộ nhớ (fix phân mảnh PSRAM):
# Baseline activations: detector 467KB, recognizer 187KB. ESP-NN scratch chỉ cần
# cho dw path opt (ch%8!=0) — đã bypass path s8pad hỏng → scratch thực tế nhỏ.
# Đặt vừa đủ để còn PSRAM cho WiFi/JPEG decode (TJpgDeco cần heap).
detector_arena_size = 1024 * 1024   # 1MB: 467KB + headroom 557KB cho scratch
recognizer_arena_size = 512 * 1024  # 512KB: 187KB + headroom 325KB
packet_buffer_size = 32 * 1024
raw_frame_size = 128
face_target_size = 64
face_embedding_dim = 128
face_threshold = 0.70
detector_conf_thresh = 0.80
temporal_votes = 3
max_templates = 16

def generate_header():
    h_content = f"""#ifndef AI_CONFIG_H
#define AI_CONFIG_H

// Auto-generated by training_tinyml/export_config.py — DO NOT EDIT MANUALLY
// Đồng bộ Laptop ↔ ESP32: RAW {raw_frame_size}x{raw_frame_size} → FACE {face_target_size}x{face_target_size}, TCP 12345, Bilinear 128→64

#define RAW_FRAME_SIZE        {raw_frame_size}
#define FACE_TARGET_SIZE      {face_target_size}
#define FACE_EMBEDDING_DIM    {face_embedding_dim}
#define FACE_THRESHOLD        {face_threshold:.2f}f
#define DETECTOR_CONF_THRESH  {detector_conf_thresh:.2f}f
#define TEMPORAL_VOTES        {temporal_votes}
#define MAX_TEMPLATES         {max_templates}
#define RECOGNIZER_ARENA_SIZE ({recognizer_arena_size})  // 512KB PSRAM: 187KB + headroom
#define DETECTOR_ARENA_SIZE   ({detector_arena_size})  // 1MB PSRAM: 467KB + headroom
#define PACKET_BUFFER_SIZE    ({packet_buffer_size})   // 32KB = 128*128*2
#define FRAME_BUFFER_SIZE     (RAW_FRAME_SIZE * RAW_FRAME_SIZE * 2)

#endif // AI_CONFIG_H
"""
    return h_content

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    out_path = os.path.join(project_root, "firmware_esp32", "ai_config.h")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(generate_header())
    print(f"[+] Generated {out_path}")
    print(f"    RECOGNIZER {recognizer_arena_size}  DETECTOR {detector_arena_size}  PACKET {packet_buffer_size}")

# Keep importable
__all__ = ["detector_arena_size", "recognizer_arena_size", "packet_buffer_size", "generate_header"]
