#ifndef AI_CONFIG_H
#define AI_CONFIG_H

// Auto-generated by training_tinyml/export_config.py — DO NOT EDIT MANUALLY
// Đồng bộ Laptop ↔ ESP32: RAW 128x128 → FACE 64x64, TCP 12345, Bilinear 128→64

#define RAW_FRAME_SIZE        128
#define FACE_TARGET_SIZE      64
#define FACE_EMBEDDING_DIM    128
#define FACE_THRESHOLD        0.60f
#define DETECTOR_CONF_THRESH  0.80f
#define TEMPORAL_VOTES        3
#define MAX_TEMPLATES         16
#define RECOGNIZER_ARENA_SIZE (524288)  // 512KB PSRAM: 187KB + headroom
#define DETECTOR_ARENA_SIZE   (1048576)  // 1MB PSRAM: 467KB + headroom
#define PACKET_BUFFER_SIZE    (32768)   // 32KB = 128*128*2
#define FRAME_BUFFER_SIZE     (RAW_FRAME_SIZE * RAW_FRAME_SIZE * 2)

#endif // AI_CONFIG_H
